baseURL = 'https://ourlittlecommunity.org/'
languageCode = 'en-us'
title = 'Our Little Community'

# [frontmatter]
  # date = [':filename', ':default']

[taxonomies]
  # tags = "tags"
  # categories = "categories"
  # month = "month"
  # year = "year"

[permalinks]
  blog = "blog/:year/:month/:slug"
  # month = "posts/:slug"
  # year = "posts/:slug"

[outputs]
  home = ["html"]

[[build.cachebusters]]
  source = 'layouts/.*'
  target = 'css'

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'
